databases:
  - name: pixel-field-db
    databaseName: pixelfield
    user: pixelfield
    plan: free

services:
  - type: web
    name: pixel-field-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pixel-field-db
          property: connectionString
      - key: ADMIN_SECRET
        value: change_me
      - key: TELEGRAM_BOT_TOKEN_FOR_WEBAPP_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_TG_ID
        value: 8458621477
